// <auto-generated />
namespace BET.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202111121618565_init_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
